import os
import subprocess
import sys
from datetime import date as date_cls, datetime, timedelta
from PyQt5.QtWidgets import (
    QApplication, QWidget, QLabel, QVBoxLayout, QHBoxLayout, QPushButton,
    QGraphicsView, QGraphicsScene, QGraphicsProxyWidget, QStackedWidget,
    QDialog, QCalendarWidget, QTableView, QHeaderView, QGraphicsDropShadowEffect,
    QComboBox
)
from PyQt5.QtCore import Qt, QTimer, QDate, QSizeF, QLocale
from PyQt5.QtGui import (QBrush, QColor, QFont, QFontMetrics, QIcon,
                         QTextCharFormat, QTransform)
# prayer_times_map.py is generated by config/scripts/02_convert_list_to_map.py and
# copied in beside this file. It is read rather than imported - see load_prayer_times.



# Resolved from this file rather than from $HOME: the icons sit beside the code in the
# same tree, so this is right whichever user owns the device and also when the app is
# started from a staging copy during an update.
ICONS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),
    "config", "icons")


def app_icon():
    """The window icon, assembled from every size that ships in config/icons/."""
    icon = QIcon()
    for size in (16, 32, 48, 64, 128, 256):
        path = os.path.join(ICONS_DIR, "athan-app-icon-%d.png" % size)
        if os.path.exists(path):
            icon.addFile(path)
    return icon

# The version this device is actually running, which is not a property of this file.
# check_updates.sh writes var/installed_version after a release passes its health check,
# so that file - not a constant baked into the payload - is the only honest answer. A
# constant here would still read "1.0.0" on a device that has taken four updates.
INSTALLED_VERSION_FILE = os.path.join(
    os.path.expanduser("~"), "Desktop", "scheduler", "var", "installed_version"
)


def installed_version():
    """Read on every refresh, never cached.

    check_updates.sh relaunches this app *before* it runs the health check, and writes
    var/installed_version only *after* the check passes. A value read once at startup
    would therefore show the previous version for the whole life of the process - which
    is exactly the moment someone looks at this label to see whether an update landed.
    """
    try:
        with open(INSTALLED_VERSION_FILE, encoding="utf-8") as handle:
            version = handle.read().strip()
    except OSError:
        return "—"
    return version if version and version != "unknown" else "—"

# =============================================================================
# APPEARANCE
# -----------------------------------------------------------------------------
# Every size, font, ratio and margin the countdown page is built from. Change a
# value here and the layout follows; nothing below hard-codes these numbers.
#
# Sizes are ratios of the window, not fixed points, and are measured against the
# font at runtime - a fixed point size is only ever correct for the one font it
# was chosen against, and this app resolves different fonts on different devices.
# Ratios are of the window's own width/height, so 0.5 is half the screen.
# =============================================================================

# --- Fonts -------------------------------------------------------------------
# Two families, by role. The Arabic label uses Amiri, the typeface this project
# ships and installs (config/fonts/arabic-fonts) and which the settings app and
# the daily table already use. Amiri's numerals are old-style and finely stroked;
# the digits keep the grotesque face the counter has always had, which reads far
# better across a room.
COUNTDOWN_NAME_FONT = "Amiri"
COUNTDOWN_DIGITS_FONT = "DejaVu Sans"
# Speaker glyphs live in Noto Sans Symbols2, which init.sh installs - DejaVu Sans
# does not carry them. A device that has not been re-initialised draws a box here.
SYMBOL_FONT = "Noto Sans Symbols2"
SPEAKER_ON = "\U0001F50A"
SPEAKER_OFF = "\U0001F507"

# --- Prayer name -------------------------------------------------------------
# Ink, not line box: Amiri reserves half again its drawn height for diacritics
# these labels never use, so sizing by QFontMetrics.height() would draw it far
# smaller than a font whose box is tight. Measuring what is actually painted
# keeps the name the same size on screen whichever family the device resolves.
COUNTDOWN_NAME_INK_RATIO = 0.265      # ink height, as a share of window height
COUNTDOWN_NAME_WIDTH_RATIO = 0.65     # ink width, as a share of window width
COUNTDOWN_NAME_INK_TOP_RATIO = 0.165  # where the ink starts, from the window top
COUNTDOWN_NAME_MAX_PT = 130           # search bounds for the fitted size
COUNTDOWN_NAME_MIN_PT = 30

# --- Countdown digits --------------------------------------------------------
COUNTDOWN_DIGITS_INK_RATIO = 0.35     # ink height, as a share of window height
COUNTDOWN_DIGITS_WIDTH_RATIO = 0.85   # ink width, as a share of window width
COUNTDOWN_DIGITS_MAX_PT = 300         # search bounds for the fitted size
COUNTDOWN_DIGITS_MIN_PT = 80
# The digits are drawn through a graphics view so they can be stretched taller
# than the font draws them, which is the look this counter has always had.
COUNTDOWN_DIGITS_STRETCH_Y = 1.35
# Nudges the digits within the height left to them. Zero because frame_digits
# hands the view the painted band instead of the whole line box, which centres
# them on its own; kept as the knob to lean on if a future font needs the help.
COUNTDOWN_SHIFT_Y = 0

# --- Margins -----------------------------------------------------------------
# The digits start at a fixed height whatever the name does, because the name is
# placed rather than laid out. Growing the name cannot push the digits down: it
# keeps its ink top and grows into the gap between the two.
COUNTDOWN_VIEW_TOP_RATIO = 0.429      # where the digits' area starts
COUNTDOWN_SIDE_MARGIN = 9
COUNTDOWN_BOTTOM_MARGIN = 9

# --- Makrooh notice ----------------------------------------------------------
# Placed on the page rather than in the layout, in the strip beside the window
# buttons. In the layout it would push the name and digits down whenever it
# appeared; out of the flow, showing or hiding it moves nothing. Capped so every
# notice renders at much the same height whatever its text.
COUNTDOWN_NOTICE_TOP = 6
COUNTDOWN_NOTICE_HEIGHT = 50
COUNTDOWN_NOTICE_MAX_PT = 22
COUNTDOWN_NOTICE_MIN_PT = 14

# --- Countdown page backgrounds ----------------------------------------------
# Deeper shades than the daily table's PERIOD_COLORS, which are read on a card
# rather than across a room. Makrooh is the exception: one orange, shared with
# the table, so both screens agree on what a makrooh window looks like.
COUNTDOWN_BG_DEFAULT = "#333333"
COUNTDOWN_BG_GREEN = "#006600"    # the 20 minutes after an athan
COUNTDOWN_BG_RED = "#990000"      # the 20 minutes before the next athan
# Both makrooh windows: from sunrise until Duha opens, and the zawal stretch at
# the end of Duha. Neither is merely "the next athan is close" - praying nafl in
# them is discouraged, so they read as their own state rather than as red.
# The deep burnt orange this counter has always used. A lighter, brighter orange
# washes out to yellow on these panels and leaves white text hard to read on it.
COUNTDOWN_BG_MAKROOH = "#BF360C"

# --- Window buttons ----------------------------------------------------------
# A row of four in the top-left corner: close, fullscreen, view, mute. Centred
# text on the notice line is shrunk until it clears them.
WINDOW_BUTTON_LEFT = 10               # x of the first button
WINDOW_BUTTON_PITCH = 48              # x step between buttons
WINDOW_BUTTON_WIDTH = 48
WINDOW_BUTTON_HEIGHT = 50
WINDOW_BUTTON_FONT_PX = 20
WINDOW_BUTTONS_RIGHT_EDGE = 210       # what the notice has to stay clear of
# Each glyph sits at a different height inside its own line box, so the four are
# nudged individually to put their ink on one line. Measured, not guessed: the
# centres were 35.5 / 35.0 / 37.5 / 36.0 before these offsets.
EXIT_ICON_Y = 10           # ✖
FULLSCREEN_ICON_Y = 11     # ⛶
# The view button swaps its glyph per page and the two sit at different heights.
VIEW_ICON_Y_COUNTER = 11   # ☰
VIEW_ICON_Y_DAILY = 8      # ◷
# The speaker glyphs draw larger and higher than the rest at a shared size, so
# they carry their own size and drop.
MUTE_ICON_Y = 14
MUTE_ICON_SIZE = 16
# The muted glyph is a ring around mostly empty space, so at the size that
# matches the others by ink box it reads lighter. It is drawn larger to make up.
MUTE_ICON_SIZE_MUTED = 20
MUTED_COLOR = "#dc3545"


# The scheduler service and this GUI run as the same desktop user, so a plain file under
# var/ is all that is needed to pass the mute state between them - no restart, no sudo.
SCHEDULER_DIR = os.path.join(os.path.expanduser("~"), "Desktop", "scheduler")
MUTE_FLAG_FILE = os.path.join(SCHEDULER_DIR, "var", "mute.flag")
PLAYER_SCRIPT_FILE = os.path.join(SCHEDULER_DIR, "config", "scripts", "play_audio.sh")
# Muting is temporary: the flag holds the epoch second the mute lapses, so the scheduler
# and the player can each honour the expiry on their own. Keeping the deadline in the
# file rather than in this process means a mute still lifts if the GUI is closed or
# restarted while it is active - otherwise the athan could stay off with no way back.
MUTE_DURATION_MINUTES = 60

# Muting acts on the output device, not on the player: an athan already playing goes
# silent at once and comes back mid-stream when unmuted. Killing the player silences it
# just as fast, but nothing can bring it back - so that is only the fallback, for a
# device where the device cannot be reached.
#
# wpctl ships with wireplumber, the session manager already running here. pactl is not
# installed on the device and amixer finds no usable Master control on this hardware.
AUDIO_SINK = "@DEFAULT_AUDIO_SINK@"
AUDIO_MUTE_CMD = ["wpctl", "set-mute", AUDIO_SINK]
AUDIO_STATE_CMD = ["wpctl", "get-volume", AUDIO_SINK]
AUDIO_CMD_TIMEOUT = 3
# The device is asked how it stands rather than trusted to still be as it was left, so
# the button cannot claim sound is on while the speaker is silent. Every second would
# fork a process a second for the life of the kiosk; two is far below noticing.
AUDIO_STATE_POLL_SECONDS = 2


def window_button_box(index, icon_y):
    """Geometry of the nth window button. Each glyph carries its own y so their ink
    lands on one line despite sitting differently inside their line boxes."""
    return (WINDOW_BUTTON_LEFT + index * WINDOW_BUTTON_PITCH, icon_y,
            WINDOW_BUTTON_WIDTH, WINDOW_BUTTON_HEIGHT)


def audio_set_mute(muted):
    """Silence or restore the output device. False if the device could not be reached."""
    try:
        subprocess.run(AUDIO_MUTE_CMD + ["1" if muted else "0"], check=True,
                       capture_output=True, timeout=AUDIO_CMD_TIMEOUT)
        return True
    except (OSError, subprocess.SubprocessError):
        return False


def audio_is_muted():
    """Whether the output device is silenced, or None if it cannot be asked."""
    try:
        state = subprocess.run(AUDIO_STATE_CMD, check=True, capture_output=True,
                               text=True, timeout=AUDIO_CMD_TIMEOUT).stdout
    except (OSError, subprocess.SubprocessError):
        return None
    return "[MUTED]" in state


def mute_expiry():
    """Epoch second this mute ends, or None if there is no readable mute in force."""
    try:
        with open(MUTE_FLAG_FILE) as flag:
            return int(flag.read().strip())
    except (OSError, ValueError):
        return None


def is_muted():
    expiry = mute_expiry()
    return expiry is not None and datetime.now().timestamp() < expiry


# -------------------------
# Build date → prayer map
# -------------------------
# Rebuilt in place rather than rebound, so every reference held elsewhere sees the new
# times: apply_settings.sh rewrites prayer_times_map.py underneath a running app - from
# the Settings GUI and from the new year's cron job - and it restarts the athan service
# but not this one. Without a reload the screen would keep showing the times it was
# started with, for as long as the kiosk stays up.
prayersByDate = {}
PRAYER_MAP_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "prayer_times_map.py")
_prayer_map_mtime = None


def load_prayer_times():
    """Re-read the generated map. False if it could not be read this time.

    Read and executed rather than imported: import would answer from the .pyc cache,
    which is judged stale only by the source's size and mtime in whole seconds. Every
    time is HH:MM, so a regenerated map is very often exactly the same size as the one
    before it, and a changed prayer time would be silently ignored. The athan service
    reads the same file the same way."""
    global _prayer_map_mtime
    namespace = {}
    try:
        stamp = os.path.getmtime(PRAYER_MAP_FILE)
        with open(PRAYER_MAP_FILE, encoding="utf-8") as handle:
            exec(handle.read(), {}, namespace)
        rows = namespace["prayerTimes"]
    except (OSError, SyntaxError, ValueError, KeyError):
        # cp -f is not atomic, so a read can land mid-write. The old times stay in
        # place and the mtime is left unrecorded, which retries on the next tick.
        return False

    prayersByDate.clear()
    for pt in rows:
        prayersByDate[f"{pt['Month']}-{pt['Day']}"] = {
            "الفجر": pt.get("Fajr"),
            "الشروق": pt.get("Sunrise"),
            "الظهر": pt.get("Dhuhr"),
            "العصر": pt.get("Asr"),
            "المغرب": pt.get("Maghrib"),
            "العشاء": pt.get("Isha"),
        }
    _prayer_map_mtime = stamp
    return True


def prayer_times_changed():
    """True when the generated map has been rewritten since it was last read."""
    try:
        return os.path.getmtime(PRAYER_MAP_FILE) != _prayer_map_mtime
    except OSError:
        return False


load_prayer_times()

prayerOrder = ["الفجر", "الشروق", "الظهر", "العصر", "المغرب", "العشاء"]




_prayer_font_cache = {}
_countdown_font_cache = {}


def _countdown_labels():
    return [prayer_display_name(name) for name in dailyPrayerOrder]


def fit_prayer_font(available_width, available_height):
    """One size for every prayer, chosen so the longest name still fits.

    Sized from the longest label rather than the one on screen: width-fitting each name
    on its own would draw الشروق far larger than صلاة المغرب, and the text would change
    size through the day. Both axes are bounded as a fraction of the window and measured
    from the painted ink, so the name comes out the same size whatever family the device
    resolves - the app ships Amiri, but a machine without it falls back to something with
    quite different metrics.
    """
    key = (available_width, available_height)
    if key in _prayer_font_cache:
        return _prayer_font_cache[key]

    labels = _countdown_labels()
    max_width = available_width * COUNTDOWN_NAME_WIDTH_RATIO
    max_ink = available_height * COUNTDOWN_NAME_INK_RATIO

    chosen = QFont(COUNTDOWN_NAME_FONT, COUNTDOWN_NAME_MIN_PT, QFont.Bold)
    for size in range(COUNTDOWN_NAME_MAX_PT, COUNTDOWN_NAME_MIN_PT - 1, -1):
        metrics = QFontMetrics(QFont(COUNTDOWN_NAME_FONT, size, QFont.Bold))
        rects = [metrics.tightBoundingRect(t) for t in labels]
        if (max(r.height() for r in rects) <= max_ink
                and max(r.width() for r in rects) <= max_width):
            chosen = QFont(COUNTDOWN_NAME_FONT, size, QFont.Bold)
            break

    _prayer_font_cache[key] = chosen
    return chosen


def prayer_name_top_margin(font, available_height):
    """Top margin that puts the name's ink at the same height for any font.

    A font with a deep ascent starts painting lower inside its own line box, so a fixed
    margin drops the name further down the screen for some families than others. The
    ascent is subtracted back out here."""
    metrics = QFontMetrics(font)
    ink_offset = metrics.ascent() + min(
        metrics.tightBoundingRect(t).top() for t in _countdown_labels())
    return max(0, round(available_height * COUNTDOWN_NAME_INK_TOP_RATIO) - ink_offset)


def fit_countdown_font(available_width, available_height):
    """Largest digits whose ink fits the height left under the name, measured the same
    way as the name so the two keep their proportion across fonts."""
    key = (available_width, available_height)
    if key in _countdown_font_cache:
        return _countdown_font_cache[key]

    max_ink = available_height * COUNTDOWN_DIGITS_INK_RATIO
    max_width = available_width * COUNTDOWN_DIGITS_WIDTH_RATIO

    chosen = QFont(COUNTDOWN_DIGITS_FONT, COUNTDOWN_DIGITS_MIN_PT, QFont.Bold)
    for size in range(COUNTDOWN_DIGITS_MAX_PT, COUNTDOWN_DIGITS_MIN_PT - 1, -1):
        font = QFont(COUNTDOWN_DIGITS_FONT, size, QFont.Bold)
        rect = QFontMetrics(font).tightBoundingRect("00:00")
        if rect.height() <= max_ink and rect.width() <= max_width:
            chosen = font
            break

    _countdown_font_cache[key] = chosen
    return chosen


def fit_notice_font(text, available_width):
    """Largest size whose centred text starts to the right of the window buttons."""
    for size in range(COUNTDOWN_NOTICE_MAX_PT, COUNTDOWN_NOTICE_MIN_PT - 1, -1):
        font = QFont(COUNTDOWN_NAME_FONT, size, QFont.Bold)
        width = QFontMetrics(font).horizontalAdvance(text)
        if (available_width - width) / 2 >= WINDOW_BUTTONS_RIGHT_EDGE:
            return font
    return QFont(COUNTDOWN_NAME_FONT, COUNTDOWN_NOTICE_MIN_PT, QFont.Bold)


def duha_window(now):
    """The stretch from الشروق to الظهر, which this page models as الضحى's own period
    rather than as a plain countdown to the الظهر athan.

    Returns (duha_start, dhuhr) while inside it, otherwise None.
    """
    times = prayersByDate.get(key_for_date(now), {})
    sunrise_str, dhuhr_str = times.get("الشروق"), times.get("الظهر")
    if not sunrise_str or not dhuhr_str:
        return None
    sunrise_dt = build_datetime(now, sunrise_str)
    dhuhr_dt = build_datetime(now, dhuhr_str)
    if not sunrise_dt <= now < dhuhr_dt:
        return None
    return sunrise_dt + timedelta(minutes=DUHA_AFTER_SUNRISE_MINUTES), dhuhr_dt


def prayer_display_name(name):
    """الشروق is neither a صلاة nor has an أذان, so it is the one entry shown bare."""
    return name if name == "الشروق" else f"صلاة {name}"


def key_for_date(d):
    return f"{d.month}-{d.day}"

def build_datetime(date, time_str):
    if not time_str:
        return None
    h, m = map(int, time_str.split(":"))
    return datetime(date.year, date.month, date.day, h, m)

def next_occurrence(prayer, now):
    today_time = prayersByDate.get(key_for_date(now), {}).get(prayer)
    if today_time:
        dt = build_datetime(now, today_time)
        if dt > now:
            return dt
    tomorrow = now + timedelta(days=1)
    tomorrow_time = prayersByDate.get(key_for_date(tomorrow), {}).get(prayer)
    if tomorrow_time:
        return build_datetime(tomorrow, tomorrow_time)
    return None

def prev_occurrence(prayer, now):
    today_time = prayersByDate.get(key_for_date(now), {}).get(prayer)
    if today_time:
        dt = build_datetime(now, today_time)
        if dt <= now:
            return dt
    yesterday = now - timedelta(days=1)
    y_time = prayersByDate.get(key_for_date(yesterday), {}).get(prayer)
    if y_time:
        return build_datetime(yesterday, y_time)
    return None

def get_prev_next_prayer(now):
    prev_p = next_p = None
    prev_t = next_t = None
    for p in prayerOrder:
        nt = next_occurrence(p, now)
        pt = prev_occurrence(p, now)
        if nt and (not next_t or nt < next_t):
            next_p, next_t = p, nt
        if pt and (not prev_t or pt > prev_t):
            prev_p, prev_t = p, pt
    return prev_p, next_p, prev_t, next_t


# -------------------------
# Daily prayer table
# -------------------------
DUHA_AFTER_SUNRISE_MINUTES = 20
# The countdown page is the reference: green for the 20 minutes after an athan, red for
# the 20 minutes before the next one.
PERIOD_EDGE_MINUTES = 20
# A date picked by hand is a temporary detour on a kiosk that nobody signs out of, so
# the table drops back to today once it has been left alone this long.
BROWSE_RESET_MINUTES = 10

# The weekday names read in Arabic; the months and years stay numbers, which need no
# translating and keep the bar narrow. Weekday names are the same in every Arabic locale,
# so the calendar takes ar_MA purely for its Western day numerals - ar_SY and its
# neighbours number the grid in Arabic-Indic digits, which would be the only place in
# the whole app to use them.
CALENDAR_LOCALE = QLocale(QLocale.Arabic, QLocale.Morocco)
# The year list opens on the current year with three either side in view, and scrolls
# from there - far easier on a touchscreen than the spin box Qt gives by default.
CALENDAR_YEARS_VISIBLE = 7
CALENDAR_YEAR_SPAN = 10

dailyPrayerOrder = ["الفجر", "الشروق", "الضحى", "الظهر", "العصر", "المغرب", "العشاء"]

MAKROOH_LABEL = "مكروه"

PERIOD_COLORS = {
    "green": "#198754",
    "beige": "#E7DBC1",
    "red": "#dc3545",
    "makrooh": COUNTDOWN_BG_MAKROOH,
}

PERIOD_TEXT = {
    "green": "#FFFFFF",
    "beige": "#4A3F2F",
    "red": "#FFFFFF",
    "makrooh": "#FFFFFF",
}

PAGE_BG = "#0F172A"
PAGE_GRADIENT = ("qlineargradient(x1:0, y1:0, x2:0, y2:1,"
                 " stop:0 #0F172A, stop:1 #1B2437)")
PAGE_TEXT = "#F8FAFC"
CARD_BG = "#1E293B"
CARD_BORDER = "#475569"
INPUT_BORDER = "#475569"
NAME_COLOR = "#F1F5F9"
TIME_COLOR = "#F1F5F9"
FOOTER_COLOR = "#64748B"


def daily_times(view_date):
    times = prayersByDate.get(key_for_date(view_date))
    if not times:
        return None
    resolved = {}
    for name in dailyPrayerOrder:
        if name == "الضحى":
            sunrise = resolved.get("الشروق")
            resolved[name] = (sunrise + timedelta(minutes=DUHA_AFTER_SUNRISE_MINUTES)
                              if sunrise else None)
        else:
            resolved[name] = build_datetime(view_date, times.get(name))
    return resolved


def daily_rows(view_date, now, is_today):
    """One entry per prayer: the time shown on the card, plus the period it opens.

    A prayer's period runs until the next prayer starts, so the running period is the
    one the current time falls into - that is the row the page highlights."""
    times = daily_times(view_date)
    if not times:
        return None

    rows = []
    for index, name in enumerate(dailyPrayerOrder):
        if index + 1 < len(dailyPrayerOrder):
            end = times[dailyPrayerOrder[index + 1]]
        else:
            next_day = daily_times(view_date + timedelta(days=1))
            end = next_day["الفجر"] if next_day else None
        rows.append({"name": name, "time": times[name], "start": times[name], "end": end})

    # Isha is the only period that crosses midnight, so between midnight and Fajr the
    # running period is yesterday evening's. The card keeps showing tonight's Isha.
    fajr = times["الفجر"]
    if is_today and fajr and now < fajr:
        yesterday = daily_times(view_date - timedelta(days=1))
        if yesterday and yesterday["العشاء"]:
            rows[-1]["start"] = yesterday["العشاء"]
            rows[-1]["end"] = fajr

    return rows


def period_state(name, start, end, now):
    """Colour of the running period, and whether praying nafl in it is makrooh.

    The two makrooh windows are the ones the countdown page already warns about: from
    sunrise until Duha opens, and the zawal stretch just before Dhuhr. The red state on
    every other period only means the next athan is close - it is not makrooh."""
    duration = int((end - start).total_seconds() // 60)
    remaining = int((end - now).total_seconds() // 60)
    if name == "الشروق":
        return "makrooh", True
    # Zawal, the close of Duha. Makrooh in its own right, so it takes the makrooh
    # colour rather than the red that only means the next athan is near - the same
    # sense the countdown page uses for this window.
    if name == "الضحى" and remaining <= PERIOD_EDGE_MINUTES:
        return "makrooh", True
    if duration - PERIOD_EDGE_MINUTES < remaining:
        return "green", False
    if remaining <= PERIOD_EDGE_MINUTES:
        return "red", False
    return "beige", False


# -------------------------
# Date picker
# -------------------------
class DatePickerDialog(QDialog):
    def __init__(self, current, parent=None):
        super().__init__(parent)
        # The window manager decorations are useless on a frameless kiosk, and their
        # buttons are too small to hit on the touchscreen anyway.
        self.setWindowFlags(Qt.Dialog | Qt.FramelessWindowHint)
        self.setLayoutDirection(Qt.RightToLeft)
        self.setStyleSheet(f"QDialog {{ background-color: {PAGE_BG};"
                           f" border: 2px solid {INPUT_BORDER}; }}")
        self.selected_date = None

        layout = QVBoxLayout(self)
        layout.setContentsMargins(10, 10, 10, 10)
        layout.setSpacing(8)

        title = QLabel("اختر التاريخ")
        title.setAlignment(Qt.AlignCenter)
        title.setFont(QFont("Amiri", 17))
        title.setStyleSheet(f"color: {PAGE_TEXT};")
        layout.addWidget(title)

        self.calendar = QCalendarWidget()
        # Gregorian dates read left to right, like the date button they came from
        self.calendar.setLayoutDirection(Qt.LeftToRight)
        self.calendar.setLocale(CALENDAR_LOCALE)
        # Qt's own bar offers the year through a spin box, which is a poor target on a
        # touchscreen and shows one year at a time. Replaced below by two dropdowns.
        self.calendar.setNavigationBarVisible(False)
        self.calendar.setGridVisible(True)
        self.calendar.setVerticalHeaderFormat(QCalendarWidget.NoVerticalHeader)
        self.calendar.setHorizontalHeaderFormat(QCalendarWidget.ShortDayNames)
        self.calendar.setSelectedDate(QDate(current.year, current.month, current.day))
        self.calendar.setStyleSheet(
            f"QCalendarWidget QWidget#qt_calendar_navigationbar {{"
            f" background-color: {CARD_BG}; }}"
            f"QCalendarWidget QToolButton {{ height: 34px; font-size: 15px;"
            f" color: {NAME_COLOR}; background-color: transparent; border: none; }}"
            f"QCalendarWidget QMenu, QCalendarWidget QSpinBox {{"
            f" background-color: {CARD_BG}; color: {NAME_COLOR}; }}"
            f"QCalendarWidget QAbstractItemView:enabled {{ font-size: 15px;"
            f" color: {NAME_COLOR}; background-color: {PAGE_BG};"
            f" gridline-color: {CARD_BORDER};"
            f" selection-background-color: {PERIOD_COLORS['makrooh']};"
            " selection-color: #FFFFFF; }"
            "QCalendarWidget QAbstractItemView:disabled { color: #64748B; }"
        )
        self.nav_style = (
            f"QComboBox {{ height: 38px; font-size: 16px; padding: 0 8px;"
            f" color: {PAGE_TEXT}; background-color: {CARD_BG};"
            f" border: 2px solid {INPUT_BORDER}; border-radius: 6px; }}"
            f"QComboBox QAbstractItemView {{ font-size: 16px;"
            f" color: {PAGE_TEXT}; background-color: {CARD_BG};"
            f" selection-background-color: {PERIOD_COLORS['makrooh']};"
            " selection-color: #FFFFFF; outline: none; }"
            f"QPushButton {{ min-width: 44px; height: 38px; font-size: 20px;"
            f" color: {PAGE_TEXT}; background-color: {CARD_BG};"
            f" border: 2px solid {INPUT_BORDER}; border-radius: 6px; }}"
        )
        # The weekday header is painted from these formats, not from the stylesheet
        header_format = QTextCharFormat()
        header_format.setForeground(QBrush(QColor(NAME_COLOR)))
        header_format.setBackground(QBrush(QColor(CARD_BG)))
        self.calendar.setHeaderTextFormat(header_format)
        for weekday in (Qt.Saturday, Qt.Sunday):
            weekend_format = QTextCharFormat()
            weekend_format.setForeground(QBrush(QColor(NAME_COLOR)))
            self.calendar.setWeekdayTextFormat(weekday, weekend_format)
        self.calendar.clicked.connect(self.pick_date)

        # Its table asks for cells far wider than this screen, which clips every column
        # past the first two - stretch the cells into the room the dialog actually has.
        table = self.calendar.findChild(QTableView, "qt_calendar_calendarview")
        if table is not None:
            table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
            table.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        layout.addWidget(self.build_nav_bar())
        layout.addWidget(self.calendar)

        cancel_btn = QPushButton("إلغاء")
        cancel_btn.setFont(QFont("Amiri", 16))
        cancel_btn.setMinimumHeight(44)
        cancel_btn.setStyleSheet(
            f"QPushButton {{ background: {CARD_BG}; color: {PAGE_TEXT};"
            f" border: 2px solid {INPUT_BORDER}; border-radius: 6px; }}"
        )
        cancel_btn.clicked.connect(self.reject)
        layout.addWidget(cancel_btn)

        self.setFixedSize(*self.dialog_size())

    def build_nav_bar(self):
        """Month and year as dropdowns, with an arrow either side for the next month.

        Carried on its own widget so it can be left to right like the grid below it,
        which stays Gregorian - in the dialog's own right-to-left flow the back arrow
        would sit on the right, pointing the opposite way to the month it moves."""
        bar = QWidget()
        bar.setLayoutDirection(Qt.LeftToRight)
        row = QHBoxLayout(bar)
        row.setContentsMargins(0, 0, 0, 0)
        row.setSpacing(6)

        prev_btn = QPushButton("‹")
        next_btn = QPushButton("›")
        prev_btn.clicked.connect(self.calendar.showPreviousMonth)
        next_btn.clicked.connect(self.calendar.showNextMonth)

        self.month_box = QComboBox()
        for month in range(1, 13):
            self.month_box.addItem(f"{month:02d}", month)
        self.year_box = QComboBox()
        self.year_box.setMaxVisibleItems(CALENDAR_YEARS_VISIBLE)

        for widget in (prev_btn, next_btn, self.month_box, self.year_box):
            widget.setStyleSheet(self.nav_style)

        shown = self.calendar.selectedDate()
        self.fill_years(shown.year())
        self.show_page(shown.year(), shown.month())

        self.month_box.activated.connect(self.nav_changed)
        self.year_box.activated.connect(self.nav_changed)
        # Keeps the dropdowns honest when the arrows move the page instead.
        self.calendar.currentPageChanged.connect(self.show_page)

        row.addWidget(prev_btn)
        row.addWidget(self.month_box, 1)
        row.addWidget(self.year_box, 1)
        row.addWidget(next_btn)
        return bar

    def fill_years(self, around):
        """A span of years centred on the one in view, so the list scrolls both ways."""
        self.year_box.blockSignals(True)
        self.year_box.clear()
        for year in range(around - CALENDAR_YEAR_SPAN, around + CALENDAR_YEAR_SPAN + 1):
            self.year_box.addItem(str(year), year)
        self.year_box.blockSignals(False)

    def show_page(self, year, month):
        """Point the dropdowns at the month on display, without steering it back."""
        if self.year_box.findData(year) < 0:
            # Arrowed past the end of the list - recentre it rather than lose the year.
            self.fill_years(year)
        for box, value in ((self.month_box, month), (self.year_box, year)):
            box.blockSignals(True)
            box.setCurrentIndex(box.findData(value))
            box.blockSignals(False)

    def nav_changed(self, _index):
        self.calendar.setCurrentPage(self.year_box.currentData(),
                                     self.month_box.currentData())

    def dialog_size(self):
        """Fit the screen the app is actually on, rather than a guessed minimum."""
        parent = self.parentWidget()
        if parent is not None and parent.width() > 100 and parent.height() > 100:
            available = parent.size()
        else:
            available = QApplication.primaryScreen().availableGeometry().size()
        return int(available.width() * 0.92), int(available.height() * 0.92)

    def showEvent(self, event):
        super().showEvent(event)
        parent = self.parentWidget()
        if parent is not None:
            center = parent.mapToGlobal(parent.rect().center())
            self.move(center.x() - self.width() // 2, center.y() - self.height() // 2)

    def pick_date(self, qdate):
        self.selected_date = date_cls(qdate.year(), qdate.month(), qdate.day())
        self.accept()


# -------------------------
# Daily prayer page
# -------------------------
class PrayerCard(QWidget):
    IDLE_HEIGHT = 42
    ACTIVE_HEIGHT = 52

    def __init__(self, name):
        super().__init__()
        self.setObjectName("prayerCard")
        # Plain QWidgets ignore a stylesheet background unless they are told to paint one
        self.setAttribute(Qt.WA_StyledBackground, True)
        self.setLayoutDirection(Qt.LeftToRight)
        self.setFixedHeight(self.IDLE_HEIGHT)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(14, 4, 14, 4)

        self.time_label = QLabel("--:--")
        self.time_label.setObjectName("prayerTime")

        self.makrooh_label = QLabel(MAKROOH_LABEL)
        self.makrooh_label.setObjectName("makroohTag")
        self.makrooh_label.hide()

        self.name_label = QLabel(name)
        self.name_label.setObjectName("prayerName")

        layout.addWidget(self.time_label)
        layout.addSpacing(10)
        layout.addWidget(self.makrooh_label)
        layout.addStretch()
        layout.addWidget(self.name_label)

        # Lifts the running prayer off the page instead of only recolouring it
        self.shadow = QGraphicsDropShadowEffect(self)
        self.shadow.setBlurRadius(16)
        self.shadow.setOffset(0, 0)
        self.shadow.setColor(QColor(0, 0, 0, 120))
        self.shadow.setEnabled(False)
        self.setGraphicsEffect(self.shadow)

        self.state = None
        self.apply_state("--:--", None)

    def apply_state(self, time_text, color, makrooh=False):
        self.time_label.setText(time_text)
        self.makrooh_label.setVisible(makrooh)

        # Restyling on every tick would repaint the whole list once a second
        state = (color, makrooh)
        if state == self.state:
            return
        self.state = state

        active = color is not None
        if active:
            base = QColor(PERIOD_COLORS[color])
            light_fill = base.lightness() > 170
            background = ("qlineargradient(x1:0, y1:0, x2:1, y2:0,"
                          f" stop:0 {base.name()},"
                          f" stop:1 {base.darker(112 if light_fill else 128).name()})")
            border = base.darker(112).name() if light_fill else base.lighter(118).name()
            name_color = time_color = PERIOD_TEXT[color]
            glow = QColor(base); glow.setAlpha(90)
            self.shadow.setColor(glow)
        else:
            background = CARD_BG
            border = CARD_BORDER
            name_color = NAME_COLOR
            time_color = TIME_COLOR

        self.setFixedHeight(self.ACTIVE_HEIGHT if active else self.IDLE_HEIGHT)
        weight = QFont.Bold if active else QFont.DemiBold
        self.time_label.setFont(QFont("DejaVu Sans Mono", 17 if active else 15, weight))
        self.makrooh_label.setFont(QFont("Amiri", 16, weight))
        self.name_label.setFont(QFont("Amiri", 22 if active else 19, weight))
        self.shadow.setEnabled(active)

        self.setStyleSheet(
            f"#prayerCard {{ background: {background};"
            f" border: 2px solid {border}; border-radius: 12px; }}"
            f"#prayerCard QLabel {{ background: transparent; border: none; }}"
            f"#prayerCard #prayerName {{ color: {name_color}; }}"
            f"#prayerCard #prayerTime {{ color: {time_color}; letter-spacing: 1px; }}"
            f"#prayerCard #makroohTag {{ color: {name_color}; }}"
        )


class DailyPrayersPage(QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("dailyPage")
        self.setAttribute(Qt.WA_StyledBackground, True)
        self.setLayoutDirection(Qt.RightToLeft)
        self.setStyleSheet(f"#dailyPage {{ background: {PAGE_GRADIENT}; }}")

        self.view_date = date_cls.today()
        # The date the calendar last read as "today", used to tell a view that is
        # tracking today from one the user pinned deliberately.
        self.last_today = self.view_date
        # When a hand-picked date was chosen, or None while the view follows today.
        self.browsed_at = None

        outer = QVBoxLayout(self)
        outer.setContentsMargins(0, 4, 0, 4)
        outer.setAlignment(Qt.AlignCenter)

        container = QWidget()
        # Wider than the phone-shaped web layout: on an 800x480 panel read from a
        # distance, the extra width buys legibility that portrait proportions do not.
        container.setFixedWidth(520)
        layout = QVBoxLayout(container)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(5)

        # Date row: the date itself is the button, with a calendar button beside it
        date_row = QWidget()
        date_row.setLayoutDirection(Qt.LeftToRight)
        date_layout = QHBoxLayout(date_row)
        date_layout.setContentsMargins(0, 0, 0, 0)
        date_layout.setSpacing(0)

        self.date_btn = QPushButton()
        self.date_btn.setFont(QFont("DejaVu Sans", 15))
        self.date_btn.setMinimumHeight(40)
        self.date_btn.setMinimumWidth(180)
        self.date_btn.setStyleSheet(
            f"QPushButton {{ background: {CARD_BG}; color: {PAGE_TEXT};"
            f" border: 2px solid {INPUT_BORDER}; border-right: none;"
            " border-top-left-radius: 10px; border-bottom-left-radius: 10px; }"
        )
        self.date_btn.clicked.connect(self.open_date_picker)

        self.calendar_btn = QPushButton("▦")
        self.calendar_btn.setFont(QFont("DejaVu Sans", 15))
        self.calendar_btn.setMinimumHeight(40)
        self.calendar_btn.setFixedWidth(52)
        self.calendar_btn.setStyleSheet(
            f"QPushButton {{ background: {CARD_BG}; color: {PAGE_TEXT};"
            f" border: 2px solid {INPUT_BORDER};"
            " border-top-right-radius: 10px; border-bottom-right-radius: 10px; }"
        )
        self.calendar_btn.clicked.connect(self.open_date_picker)

        date_layout.addStretch()
        date_layout.addWidget(self.date_btn)
        date_layout.addWidget(self.calendar_btn)
        date_layout.addStretch()
        layout.addWidget(date_row)

        self.today_btn = QPushButton("اليوم")
        self.today_btn.setFont(QFont("Amiri", 14))
        self.today_btn.setMinimumHeight(30)
        self.today_btn.setStyleSheet(
            "QPushButton { background: transparent; color: #60A5FA;"
            " border: 2px solid #60A5FA; border-radius: 6px; padding: 2px 10px; }"
        )
        self.today_btn.clicked.connect(self.go_today)
        today_row = QHBoxLayout()
        today_row.addStretch()
        today_row.addWidget(self.today_btn)
        today_row.addStretch()
        layout.addLayout(today_row)

        self.badge = QLabel("--:--")
        self.badge.setAlignment(Qt.AlignCenter)
        self.badge.setFont(QFont("DejaVu Sans Mono", 17, QFont.Bold))
        self.badge.setMinimumHeight(38)
        self.badge.setFixedWidth(130)
        self.badge_glow = QGraphicsDropShadowEffect(self.badge)
        self.badge_glow.setBlurRadius(26)
        self.badge_glow.setOffset(0, 0)
        self.badge.setGraphicsEffect(self.badge_glow)
        badge_row = QHBoxLayout()
        badge_row.addStretch()
        badge_row.addWidget(self.badge)
        badge_row.addStretch()
        layout.addLayout(badge_row)

        # Own layout so the gap between cards can be wider than the gap between the
        # header rows, and so the active card's glow has room instead of being clipped
        cards_layout = QVBoxLayout()
        cards_layout.setContentsMargins(14, 2, 14, 2)
        cards_layout.setSpacing(7)
        self.cards = {}
        for name in dailyPrayerOrder:
            card = PrayerCard(name)
            self.cards[name] = card
            cards_layout.addWidget(card)
        self.cards_layout = cards_layout
        layout.addLayout(cards_layout)

        self.footer = QLabel(installed_version())
        self.footer.setAlignment(Qt.AlignCenter)
        self.footer.setFont(QFont("DejaVu Sans", 9))
        self.footer.setStyleSheet(f"color: {FOOTER_COLOR};")
        layout.addWidget(self.footer)

        outer.addWidget(container, alignment=Qt.AlignHCenter)

    # -------------------------
    # Date handling
    # -------------------------
    def open_date_picker(self):
        dialog = DatePickerDialog(self.view_date, self)
        if dialog.exec_() == QDialog.Accepted and dialog.selected_date:
            self.view_date = dialog.selected_date
            # Only arm the fallback for a genuine detour - picking today from the
            # calendar leaves the view following the calendar as before.
            self.browsed_at = (None if self.view_date == date_cls.today()
                               else datetime.now())
            self.refresh()

    def go_today(self):
        self.view_date = date_cls.today()
        self.browsed_at = None
        self.refresh()

    # -------------------------
    # Rendering
    # -------------------------
    def refresh(self):
        now = datetime.now()
        today = now.date()

        # This page is left open for days at a time, so the date it is pinned to has to
        # follow the calendar over midnight. Only a view that was tracking today moves;
        # a date the user picked by hand stays where they put it.
        if self.view_date == self.last_today:
            self.view_date = today
        self.last_today = today

        if (self.browsed_at is not None
                and (now - self.browsed_at).total_seconds() >= BROWSE_RESET_MINUTES * 60):
            self.browsed_at = None
            self.view_date = today

        is_today = self.view_date == today

        self.footer.setText(installed_version())
        self.date_btn.setText(self.view_date.strftime("%Y-%m-%d"))
        self.today_btn.setVisible(not is_today)

        rows = daily_rows(self.view_date, now, is_today)
        if not rows:
            self.badge.hide()
            for name in dailyPrayerOrder:
                self.cards[name].apply_state("--:--", None)
            return

        current_color = None
        current_remaining = None
        for row in rows:
            color = None
            makrooh = False
            if is_today and row["start"] and row["end"] and row["start"] <= now < row["end"]:
                color, makrooh = period_state(row["name"], row["start"], row["end"], now)
                current_color = color
                current_remaining = int((row["end"] - now).total_seconds() // 60)
            text = row["time"].strftime("%H:%M") if row["time"] else "--:--"
            self.cards[row["name"]].apply_state(text, color, makrooh)

        # A card that just grew or shrank leaves the layout stale, which shows up as an
        # uneven gap beside the active row until something else forces a re-layout.
        self.cards_layout.activate()

        if current_color is None:
            self.badge.hide()
            return

        hours = current_remaining // 60
        minutes = current_remaining % 60
        self.badge.setText(f"{hours:02d}:{minutes:02d}")
        base = QColor(PERIOD_COLORS[current_color])
        self.badge.setStyleSheet(
            f"color: {PERIOD_TEXT[current_color]};"
            " background: qlineargradient(x1:0, y1:0, x2:1, y2:1,"
            f" stop:0 {base.lighter(112).name()}, stop:1 {base.darker(122).name()});"
            f" border: 2px solid {base.lighter(118).name()};"
            " border-radius: 20px; padding: 4px 14px;"
        )
        glow = QColor(base); glow.setAlpha(120)
        self.badge_glow.setColor(glow)
        self.badge.show()


# -------------------------
# PyQt5 UI
# -------------------------
class AdhanCounter(QWidget):
    def __init__(self):
        super().__init__()

        self.setWindowFlags(Qt.FramelessWindowHint)
        self.setWindowTitle("عداد الأذان")
        self.setWindowIcon(app_icon())
        self.setLayoutDirection(Qt.RightToLeft)

        # Countdown page
        self.counter_page = QWidget()
        self.counter_page.setObjectName("counterPage")
        self.counter_page.setAttribute(Qt.WA_StyledBackground, True)

        # Layout
        self.layout = QVBoxLayout()
        self.layout.setAlignment(Qt.AlignCenter)
        # Replaced by prayer_name_top_margin on the first update, which happens before
        # the window is shown.
        self.layout.setContentsMargins(COUNTDOWN_SIDE_MARGIN, 0,
                                       COUNTDOWN_SIDE_MARGIN, COUNTDOWN_BOTTOM_MARGIN)

        # Labels
        # Set per tick by update_countdown(); only ever holds the makrooh warning.
        self.title = QLabel("")
        self.prayerName = QLabel("")
        self.countdown = QLabel("--:--")

        self.title.setAlignment(Qt.AlignCenter)
        self.prayerName.setAlignment(Qt.AlignCenter)
        self.countdown.setAlignment(Qt.AlignCenter)

        # --------- COUNTDOWN CONFIG ---------
        self.countdown.setFont(fit_countdown_font(800, 480))
        self.countdown.setAttribute(Qt.WA_TranslucentBackground)
        self.countdown.setStyleSheet("background: transparent; color: white;")

        self.scene = scene = QGraphicsScene(self)
        self.proxy = QGraphicsProxyWidget()
        self.proxy.setWidget(self.countdown)

        # Set Initial Transform (Standard V1 Look)
        self.proxy.setTransform(QTransform().scale(1.0, COUNTDOWN_DIGITS_STRETCH_Y))

        self.view = view = QGraphicsView(scene)
        scene.addItem(self.proxy)
        view.setAlignment(Qt.AlignCenter)
        view.setStyleSheet("background: transparent; border: none;")
        view.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        view.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)


        self.layout.addWidget(view)

        scene.setBackgroundBrush(Qt.transparent)
        view.setBackgroundBrush(Qt.transparent)
        view.setAttribute(Qt.WA_TranslucentBackground)
        # ----------------------------------------------------------

        self.counter_page.setLayout(self.layout)

        # Sits over the page, spanning its full width so the text stays centred on the
        # page; fit_notice_font keeps it narrow enough to clear the window buttons.
        # Placed, not laid out - see COUNTDOWN_VIEW_TOP_RATIO.
        self.prayerName.setParent(self.counter_page)

        self.title.setParent(self.counter_page)
        self.title.setGeometry(0, COUNTDOWN_NOTICE_TOP, 800, COUNTDOWN_NOTICE_HEIGHT)
        self.title.raise_()

        # Fonts
        self.title.setFont(QFont(COUNTDOWN_NAME_FONT, 30))
        self.prayerName.setFont(QFont(COUNTDOWN_NAME_FONT, 70))

        # Pages
        self.daily_page = DailyPrayersPage()

        self.stack = QStackedWidget()
        self.stack.addWidget(self.counter_page)
        self.stack.addWidget(self.daily_page)

        root_layout = QVBoxLayout(self)
        root_layout.setContentsMargins(0, 0, 0, 0)
        root_layout.addWidget(self.stack)

        # Exit button
        self.exit_btn = QPushButton("✖", self)
        self.exit_btn.setGeometry(*window_button_box(0, EXIT_ICON_Y))
        self.exit_btn.clicked.connect(QApplication.instance().quit)
        self.exit_btn.show()

        # Fullscreen toggle
        self.fullscreen_btn = QPushButton("⛶", self)
        self.fullscreen_btn.setGeometry(*window_button_box(1, FULLSCREEN_ICON_Y))
        self.fullscreen_btn.clicked.connect(self.toggle_fullscreen)
        self.fullscreen_btn.show()

        # Switch between the countdown and the daily prayer table
        self.view_btn = QPushButton("☰", self)
        self.view_btn.setGeometry(*window_button_box(2, VIEW_ICON_Y_COUNTER))
        self.view_btn.clicked.connect(self.toggle_view)
        self.view_btn.show()

        # Silences every scheduled athan until it is tapped again. WINDOW_BUTTON_PITCH
        # is 48 rather than the original 60 because a fourth button at the old pitch
        # reached x=240, and the centred countdown title starts at x=225.
        self.mute_btn = QPushButton(SPEAKER_ON, self)
        self.mute_btn.setGeometry(*window_button_box(3, MUTE_ICON_Y))
        self.mute_btn.clicked.connect(self.toggle_mute)
        self.mute_btn.show()
        # Counts down to the next reading of the device; zero forces one on the next
        # tick. None means the device has not been read yet, or cannot be read at all.
        self.audio_poll_due = 0
        self.audio_sink_muted = None

        # A launch is a clean slate. Whatever left the device silent - a mute that
        # outlived the app, a crash part way through one - is lifted here, along with
        # the flag that goes with it, so the app can never come up unable to be heard
        # with nothing on screen to say why. The flag goes too: leaving it would keep
        # the scheduler skipping athans while the button reported sound as on.
        self.muted = False
        self.clear_mute_flag()
        # A kiosk starts this app as it starts the audio session, so the device may not
        # answer yet. Keep asking rather than coming up silent on a lost race.
        self.force_unmute_pending = not self.set_audio_muted(False)

        btn_style = """
        QPushButton {
            color: black !important;
            background: transparent;
            border: none;
            font-size: %dpx;
        }
        """ % WINDOW_BUTTON_FONT_PX
        self.btn_style = btn_style
        self.page_button_color = "black"
        self.paint_window_buttons("black")

        for button in (self.exit_btn, self.fullscreen_btn, self.view_btn,
                       self.mute_btn):
            button.raise_()
            # Subpixel antialiasing tints thin strokes orange on one edge and blue on
            # the other. On the speaker's sound waves that is strong enough to read as
            # colour, which would compete with the red that means muted.
            icon_font = button.font()
            icon_font.setStyleStrategy(QFont.PreferAntialias | QFont.NoSubpixelAntialias)
            button.setFont(icon_font)

        # Timer
        self.timer = QTimer()
        self.timer.timeout.connect(self.tick)
        self.timer.start(1000)

        # Every font is now fitted to the window, so the window has to know its size
        # before the first fit. X11 grants fullscreen asynchronously - ask for it and
        # width() still reads the pre-fullscreen default for a frame - so the geometry
        # is taken from the screen up front and the first paint is already right.
        screen = QApplication.primaryScreen()
        if screen is not None:
            self.resize(screen.geometry().size())

        self._ready = True
        self.showFullScreen()
        self.update_countdown()

    # -------------------------
    # View switching
    # -------------------------
    def paint_window_buttons(self, color):
        style = self.btn_style.replace("color: black !important;", f"color: {color};")
        for button in (self.exit_btn, self.fullscreen_btn, self.view_btn):
            button.setStyleSheet(style)
        self.page_button_color = color
        self.paint_mute_button()

    # -------------------------
    # Mute handling
    # -------------------------
    def paint_mute_button(self):
        """Sized on its own because the speaker sits lighter than the other three icons
        at the size they share."""
        color = MUTED_COLOR if self.muted else self.page_button_color
        self.mute_btn.setText(SPEAKER_OFF if self.muted else SPEAKER_ON)
        size = MUTE_ICON_SIZE_MUTED if self.muted else MUTE_ICON_SIZE
        self.mute_btn.setStyleSheet(
            "QPushButton { background: transparent; border: none;"
            f" font-size: {size}px; font-weight: bold; color: {color}; }}")
        icon_font = QFont(SYMBOL_FONT)
        icon_font.setStyleStrategy(QFont.PreferAntialias | QFont.NoSubpixelAntialias)
        self.mute_btn.setFont(icon_font)

    def toggle_mute(self):
        """The flag governs athans still to come; the device governs the one playing now.

        Both are set together so the button means one thing - sound off - rather than
        two that can disagree."""
        # A tap settles it either way, so a launch-time unmute still owed is dropped.
        self.force_unmute_pending = False
        if self.muted:
            self.clear_mute_flag()
            self.muted = False
            self.set_audio_muted(False)
        else:
            deadline = datetime.now() + timedelta(minutes=MUTE_DURATION_MINUTES)
            os.makedirs(os.path.dirname(MUTE_FLAG_FILE), exist_ok=True)
            with open(MUTE_FLAG_FILE, "w") as flag:
                flag.write(f"{int(deadline.timestamp())}\n")
            self.muted = True
            # Only if the device cannot be silenced is the player killed instead. That
            # silences it just as fast but cannot be undone, so it is the last resort.
            if not self.set_audio_muted(True):
                self.stop_current_audio()
        self.paint_mute_button()

    def set_audio_muted(self, muted):
        """Silence or restore the device, and remember how it was left so the button is
        right at once rather than at the next reading."""
        done = audio_set_mute(muted)
        self.audio_sink_muted = muted if done else None
        self.audio_poll_due = AUDIO_STATE_POLL_SECONDS
        return done

    def clear_mute_flag(self):
        try:
            os.remove(MUTE_FLAG_FILE)
        except FileNotFoundError:
            pass
        except OSError:
            pass

    def stop_current_audio(self):
        """Muting part way through an athan should cut what is already playing. The
        player script kills its own vlc child from its EXIT trap, so signalling the
        script is enough - and it runs as this same user, so no sudo is involved."""
        try:
            subprocess.run(["pkill", "-TERM", "-f", PLAYER_SCRIPT_FILE], check=False)
        except OSError:
            pass

    def sync_mute_state(self):
        """The flag can also be cleared from a shell, so follow the file, not just taps.
        This is where a lapsed mute is tidied away: the readers already ignore an expired
        deadline, but removing the file keeps them from having to parse it every event.

        A lapsed mute also gives the device its sound back. Without that the speaker
        would stay silent with nothing left on screen or on disk to say why."""
        if self.force_unmute_pending:
            self.force_unmute_pending = not self.set_audio_muted(False)

        muted = is_muted()
        if not muted and os.path.exists(MUTE_FLAG_FILE):
            self.clear_mute_flag()
            self.set_audio_muted(False)

        # The device is read on a slower beat than the tick, so the last reading is kept
        # rather than re-derived: recomputing from the flag in between would flip the
        # button back and forth between polls.
        self.audio_poll_due -= 1
        if self.audio_poll_due <= 0:
            self.audio_poll_due = AUDIO_STATE_POLL_SECONDS
            self.audio_sink_muted = audio_is_muted()

        # The button reports the speaker, not the intent: whatever silenced the device,
        # showing sound as on while nothing can be heard would be the one useless state.
        # None means there is no device to ask - on that fallback path the player was
        # killed rather than silenced, so the flag is all there is to go on.
        if self.audio_sink_muted is not None:
            muted = self.audio_sink_muted

        if muted != self.muted:
            self.muted = muted
            self.paint_mute_button()

    def toggle_view(self):
        if self.stack.currentWidget() is self.counter_page:
            # Always open the table on today, whatever date was last browsed
            self.daily_page.go_today()
            self.stack.setCurrentWidget(self.daily_page)
            self.view_btn.setText("◷")
            self.view_btn.setGeometry(*window_button_box(2, VIEW_ICON_Y_DAILY))
            self.paint_window_buttons(PAGE_TEXT)
        else:
            self.stack.setCurrentWidget(self.counter_page)
            self.view_btn.setText("☰")
            self.view_btn.setGeometry(*window_button_box(2, VIEW_ICON_Y_COUNTER))
            self.paint_window_buttons("black")
            self.update_countdown()

    def tick(self):
        self.sync_mute_state()
        # Nothing downstream caches the times - daily_times reads prayersByDate on
        # every call - so refreshing the dict is the whole job. The refresh below
        # then redraws whichever page is showing with the new times.
        if prayer_times_changed():
            load_prayer_times()
        if self.stack.currentWidget() is self.daily_page:
            self.daily_page.refresh()
        else:
            self.update_countdown()

    # -------------------------
    # Countdown logic
    # -------------------------
    def frame_digits(self, proxy_pos_y, proxy_scale_y):
        """Show the view the digits, not the line box around them.

        A font's line box can stand well clear of the glyphs inside it - room for accents
        and descenders these digits never use. Left alone the view centres that empty box,
        which drops the digits low and crops them at its edge. Framing the painted band
        instead centres the digits themselves, whatever the font."""
        # A proxy keeps whatever size it was given; it does not grow when the widget's
        # font does. Left alone the label stays at its construction width and the digits
        # are clipped by their own label, off centre inside a scene rect sized for the
        # text they were meant to have.
        self.proxy.resize(QSizeF(self.countdown.sizeHint()))

        metrics = QFontMetrics(self.countdown.font())
        ink = metrics.tightBoundingRect("00:00")
        top_in_label = metrics.ascent() + ink.top()
        self.scene.setSceneRect(
            0,
            proxy_pos_y + top_in_label * proxy_scale_y,
            self.countdown.sizeHint().width(),
            ink.height() * proxy_scale_y,
        )

    def update_countdown(self):
        now = datetime.now()
        prev_p, next_p, prev_t, next_t = get_prev_next_prayer(now)

        if not next_t or not prev_t:
            self.countdown.setText("--:--")
            self.paint_counter_page("#808080")
            return

        # =========================================================
        # 1. ESTABLISH BASELINE (Exact Version 1 Settings)
        # =========================================================
        # We reset these every second so normal cases look normal.

        # Text
        # The small line is now only ever the makrooh warning; the prayer name below
        # says what is being counted down to.
        title_text = ""

        # Fonts are chosen at apply-time from the text that ends up being shown.

        # Positioning & Scale
        proxy_pos_y = COUNTDOWN_SHIFT_Y
        proxy_scale_y = COUNTDOWN_DIGITS_STRETCH_Y

        # Background
        bg = COUNTDOWN_BG_DEFAULT

        # =========================================================
        # 2. CALCULATE TIME
        # =========================================================
        remaining = int((next_t - now).total_seconds())
        hours = remaining // 3600
        minutes = (remaining % 3600) // 60

        self.countdown.setText(f"{hours:02d}:{minutes:02d}")

        # The name is the period now in force, not the athan being counted down to - the
        # same sense the الشروق and الضحى branches below already use.
        label = prayer_display_name(prev_p)

        since_prev = (now - prev_t).total_seconds()

        # =========================================================
        # 3. CONDITIONAL LOGIC (Only override if needed)
        # =========================================================

        window = duha_window(now)

        # The الشروق -> الظهر stretch belongs to الضحى: makrooh until الضحى opens, then
        # an ordinary period with its own green start and red (zawal) finish.
        if window:
            duha_start, dhuhr_dt = window
            edge = timedelta(minutes=PERIOD_EDGE_MINUTES)

            if now < duha_start:
                # Still الشروق's own window - name it as such; الضحى has not opened yet.
                label = prayer_display_name("الشروق")
                bg = COUNTDOWN_BG_MAKROOH
                title_text = "(الوقت مكروه لصلاة الضحى)"
                target = duha_start
            else:
                label = prayer_display_name("الضحى")
                target = dhuhr_dt
                if now < duha_start + edge:
                    bg = COUNTDOWN_BG_GREEN
                elif dhuhr_dt - now <= edge:
                    # Zawal is makrooh, not just "Dhuhr is close" - so it takes the
                    # makrooh orange, the same as the sunrise window above, rather
                    # than the red that only means the next athan is near.
                    bg = COUNTDOWN_BG_MAKROOH
                    title_text = "(الوقت مكروه لصلاة الضحى)"

            remaining = max(0, int((target - now).total_seconds()))
            hours = remaining // 3600
            minutes = (remaining % 3600) // 60
            self.countdown.setText(f"{hours:02d}:{minutes:02d}")

        # A. Green: Post-Athan (0 to 20 mins) - Standard Layout
        elif 0 <= since_prev <= 1200 and prev_p != "الشروق":
            bg = COUNTDOWN_BG_GREEN

        # B. Red: Pre-Athan Warning (Last 20 mins)
        elif 0 < remaining <= 1200:
            bg = COUNTDOWN_BG_RED

        # =========================================================
        # 4. APPLY SETTINGS
        # =========================================================

        # Apply Fonts
        width = self.width() or 800
        height = self.height() or 480
        name_font = fit_prayer_font(width, height)
        self.prayerName.setFont(name_font)

        top_margin = prayer_name_top_margin(name_font, height)
        self.title.setText(title_text)
        self.prayerName.setText(label)
        self.prayerName.setGeometry(
            COUNTDOWN_SIDE_MARGIN, top_margin,
            max(0, width - 2 * COUNTDOWN_SIDE_MARGIN),
            QFontMetrics(name_font).height())
        self.prayerName.raise_()
        # An empty label still claims a line box, which would leave a gap where the old
        # static title used to sit.
        self.title.setVisible(bool(title_text))
        self.title.setGeometry(0, COUNTDOWN_NOTICE_TOP, width, COUNTDOWN_NOTICE_HEIGHT)
        # One cap for every state: the notice is out of the layout, so it no longer
        # competes with the name for height and the name need not shrink for it.
        if title_text:
            self.title.setFont(fit_notice_font(title_text, width))
        self.countdown.setFont(fit_countdown_font(width, height))
        self.layout.setContentsMargins(
            COUNTDOWN_SIDE_MARGIN, round(height * COUNTDOWN_VIEW_TOP_RATIO),
            COUNTDOWN_SIDE_MARGIN, COUNTDOWN_BOTTOM_MARGIN)

        # Apply Graphics Transform & Position
        self.proxy.setPos(0, proxy_pos_y)
        self.proxy.setTransform(QTransform().scale(1.0, proxy_scale_y))
        self.frame_digits(proxy_pos_y, proxy_scale_y)

        # Apply Colors
        self.paint_counter_page(bg)

    def paint_counter_page(self, bg):
        """Scoped to the countdown page so the daily table keeps its own light theme."""
        self.counter_page.setStyleSheet(
            f"#counterPage {{ background: {bg}; }}"
            "#counterPage QLabel { color: white; }"
        )

    # -------------------------
    # Fullscreen handling
    # -------------------------
    def resizeEvent(self, event):
        """Fonts are fitted to the window, and X11 grants fullscreen asynchronously - the
        first update runs while the window is still at its pre-fullscreen size, so every
        font comes out small and stays that way until the next tick a second later.
        Re-fitting here puts the right sizes up on the frame the window actually reaches
        its size, and keeps them right across the fullscreen/maximised toggle."""
        super().resizeEvent(event)
        if not getattr(self, "_ready", False) or getattr(self, "_refitting", False):
            return
        self._refitting = True
        try:
            self.update_countdown()
        finally:
            self._refitting = False

    def toggle_fullscreen(self):
        if self.isFullScreen():
            self.showMaximized()
        else:
            self.showFullScreen()

    def keyPressEvent(self, event):
        if event.key() == Qt.Key_F11:
            self.toggle_fullscreen()
        elif event.key() == Qt.Key_Escape and self.isFullScreen():
            self.showMaximized()

# -------------------------
# Run app
# -------------------------
if __name__ == "__main__":
    app = QApplication(sys.argv)
    # The panel's task list is handed a window's app_id and nothing else, and for an
    # XWayland window that app_id is the WM_CLASS Qt derives from argv[0] - "main.py",
    # which is also what the Settings app reports and which matches no desktop entry.
    # With no entry to resolve, the panel falls back to the process behind the window,
    # python3, and draws the Python logo. Nothing here matches this app by class - the
    # updater and the health check both go by the command line - so naming it after its
    # own desktop entry costs nothing and gives the panel something to find.
    app.setApplicationName("prayer_times_gui")
    app.setDesktopFileName("prayer_times_gui")
    window = AdhanCounter()
    window.show()
    sys.exit(app.exec_())
